### ISSUE TITLE
Bug? There is no fit_class.label

### ISSUE THREAD

**Issue by Surflyan** [Cogito2012/GLBS#1]
![image](https://user-images.githubusercontent.com/22428303/53537255-4ef4ed00-3b44-11e9-84ad-6876397336dc.png)

**Comment by Cogito2012** [comment]
@Surflyan Thank you for your interest.
It's strange to have this kind of problem. I have checked the code and it works fine. 
You should check whether the trained model file is correctly loaded, i.e., `./models_India_150/GLBS/model_1.mat`.
Also, you should check whether your Glmnet Tool is obtained from here [Glmnet](http://web.stanford.edu/~hastie/glmnet_matlab/download.html)

Hope this can help you.

**Comment by Surflyan** [comment]
Thanks for your reply. The model_1.mat has been load successfully. But there is no label field. It need the length of label , I guess it is the length of beta.
![image](https://user-images.githubusercontent.com/22428303/53538521-ff64f000-3b48-11e9-9a67-001cd5a1e3d5.png)
Could you tell me how to set the number of selected bands? I'm hard to find it.

**Comment by Cogito2012** [comment]
@Surflyan Correct, you can get the length of beta as the number of class.

The lasso based method cannot specify the number of selected bands before training.
For the GLBS case, all sets of selected bands in terms of all the possible lambdas are provided.
For the GLBSCV case, the cross-validation is implemented so that the minimum lambda is given to get the optimal selected band sets.

Since the selected band sequences are approximately incremental, you can set the number of selected bands (such as N) in the test stage, and obtain the top-N bands as the results.

**Comment by Surflyan** [comment]
@Cogito2012  Thank you!  I see. The work you did is great！
